vigi/routes/recordings.py
"""
This module contains the flask blueprint for the recordings page.
"""

import os
import logging
from pathlib import Path
from glob import glob

from flask import Blueprint, redirect, url_for, render_template, current_app, send_file, request
from vigi.utils.media import generate_preview, read_video_file_meta

from vigi.cache import cache
from vigi.database import Database

recordings_blueprint = Blueprint('recordings', __name__)

@recordings_blueprint.route('/recordings/<camera_id>/<date>/<time>/preview')
@cache.cached(timeout=24*60*60) # Cache the preview for 24 hours as it's a unlikely to change
def preview(camera_id, date, time):
    """
    Returns the preview image for the given camera_id, date and time
    """
    video_path = _video_file_path(camera_id, date, time)

    if not os.path.exists(video_path):
        return "Video not found", 404

    # get the path without the file extension
    video_preview_path = os.path.splitext(video_path)[0] + ".jpg"

    # check if a cached preview exists
    if os.path.exists(video_preview_path):
        # return the cached preview
        with open(video_preview_path, "rb") as f:
            return f.read(), 200, {'Content-Type': 'image/jpeg'}
    else:
        # generate a new preview
        jpg = generate_preview(video_path)

        if jpg is None:
            return(redirect(url_for('static', filename='no_preview_available.jpg')))

        return jpg, 200, {'Content-Type': 'image/jpeg'}


@recordings_blueprint.route('/recordings/<camera_id>/<date>/<time>/video')
def video(camera_id, date, time):
    """
    Returns the video file for the given camera_id, date and time
    """
    video_path = _video_file_path(camera_id, date, time)

    if not os.path.exists(video_path):
        return "Video not found", 404

    # if download=true is in the query string, the video will be downloaded
    as_attachment = request.args.get("download") == "true"

    return send_file(video_path, as_attachment=as_attachment)


# delete recording
@recordings_blueprint.route('/recordings/<camera_id>/<date>/<time>/delete', methods=['DELETE'])
def delete(camera_id, date, time):
    """
    Deletes the recording for the given camera_id, date and time
    """
    logging.info("Deleting recording: %s/%s/%s", camera_id, date, time)
    database = Database(current_app.configuration_manager.db_path)
    video_path = _video_file_path(camera_id, date, time)

    # delete video file
    if os.path.exists(video_path):
        os.remove(video_path)

    # delete meta data from database
    database.delete_recording(date, time, camera_id)
    database.close()

    # return 200
    return "", 200


@recordings_blueprint.route('/recordings')
def index():
    """
    Returns a list of all recordings
    """
    database = Database(current_app.configuration_manager.db_path)
    recording_path = current_app.configuration_manager.data_dir

    recordings = glob(os.path.join(recording_path, "**", "**", "*.mp4"))

    # check if recordings exist
    if len(recordings) == 0:
        return render_template('recordings/index.html', recording_dates=[])

    # get all unique recording dates from file names and sort them
    recording_dates = {os.path.basename(Path(file).parent) for file in recordings}
    recording_dates = list(recording_dates)
    recording_dates.sort(reverse=True)

    # for each file, get all relevant information and store it in a dictionary
    recordings = {}
    for recording_date in recording_dates:
        recordings[recording_date] = []

        for file in glob(os.path.join(recording_path, "**", recording_date, "*.mp4")):
            camera_id = Path(file).parent.parent.name.split("_")[1]
            time = Path(file).stem
            meta = read_video_file_meta(file)
            duration = 0
            if meta:
                duration = meta.get("duration")

            recording_info = {
                "time": time,
                "duration": duration,
                "camera_id": camera_id,
            }

            # find meta data for the recording in the database
            meta = database.find_recording(recording_date, time, camera_id)
            if meta:
                recording_info["tags"] = meta["tags"]

            recordings[recording_date].append(recording_info)

        # sort recordings by time
        recordings[recording_date].sort(key=lambda x: x["time"], reverse=True)

    database.close()

    return render_template('recordings/index.html',
                           recording_dates=recording_dates,
                           recordings=recordings)


def _video_file_path(camera_id, date, time):
    """
    Returns the absolute path to the video file for the given camera_id, date and time
    """
    recording_path = current_app.configuration_manager.data_dir
    camera_id_dir = f"camera_{camera_id}"
    return os.path.abspath(os.path.join(recording_path, camera_id_dir, date, f"{time}.mp4"))

vigi/templates/recordings/index.html
{% extends "base.html" %}

{% block title %}Recordings{% endblock %}
{% block content %}
<div class="container">
  <h1>Recordings</h1>

  {% if recording_dates | length == 0 %}
    <div class="alert alert-warning" role="alert">
      No recordings so far. The recordings will be displayed here once the camera detects any motion.
    </div>
  {% endif %}

  <div class="accordion" id="accordion_recording_dates">
    {% for recording_date in recording_dates %}
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ recording_date }}" aria-expanded="true" aria-controls="collapseOne">
            {{ format_date(recording_date).capitalize() }} ({{ recordings[recording_date] | length }} recordings)
          </button>
        </h2>
        <div id="collapse{{ recording_date }}" class="accordion-collapse collapse recording_date_section" data-bs-parent="#accordion_recording_dates" data-date="{{ recording_date }}">
          <div class="accordion-body">
            <div class="d-flex align-content-start flex-wrap">
              {% for recording in recordings[recording_date] %}
                <a data-bs-toggle="modal" data-bs-target="#recording_video_modal">
                  <div class="recording_card card m-2" style="width: 18rem;"
                      data-camera-id="{{ recording["camera_id"] }}"
                      data-time="{{ recording["time"] }}"
                      data-tags="{{ recording.get("tags") }}">
                    <img src="{{ url_for('recordings.preview', camera_id = recording["camera_id"], date = recording_date, time = recording["time"]) }}" class="card-img-top">
                    <div class="card-body">
                      <p class="card-text">
                        {{ format_time(recording["time"]) }}
                        {{ format_duration(recording["duration"]) }}
                      </p>
                    </div>
                  </div>
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<!-- Modal to show the video recording -->
<div class="modal fade" id="recording_video_modal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="modalTitle">Video title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <video controls>
          <source id="video_source" src="" type="video/mp4">
          Your browser does not support the video tag.
        </video>
        <div>
          Detected objects: <span id="tags" class="m-0 border-0"></span>
        </div>
      </div>
      <div class="modal-footer">
        <a id="download_link" class="btn btn-primary" href="" download>Download</a>
        <a id="share_link" class="btn btn-primary" href="">
          <!-- The SVG icon was taken from: https://icons.getbootstrap.com/icons/share/ -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share" viewBox="0 0 16 16">
            <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.5 2.5 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5m-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/>
          </svg>
          Share
        </a>
        <a id="delete_link" class="btn btn-danger" href="">
          <!-- The SVG icon was taken from: https://icons.getbootstrap.com/icons/trash/ -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
          </svg>
          Delete
        </a>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}