vigi/routes/camera.py
"""
This module contains the camera routes blueprint.
"""

import cv2
import numpy as np

from flask import Blueprint, current_app, Response

camera_blueprint = Blueprint('camera', __name__)

def generate_frames(camera_monitor):
    """Generate frames from the camera and send them to the client."""

    # For development, we can run flask without the camera monitor
    # because we don't have a camera connected to the development machine
    # and because we need to restart the server every time we change the code
    stream = None
    if camera_monitor:
        stream = camera_monitor.frame_stream.subscribe()

    try:
        while True:
            # Get the frame from the stream
            if stream:
                frame = stream.get()
            else:
                # generate a black frame for the development environment
                frame = np.zeros((360, 640, 3), dtype=np.uint8)

                # Add no signal text
                font = cv2.FONT_HERSHEY_SIMPLEX
                cv2.putText(frame, 'No signal', (50, 100), font, 2, (255, 255, 255), 2, cv2.LINE_AA)

            # Convert the frame to JPEG
            _ret, jpeg = cv2.imencode('.jpg', frame)

            # Convert the JPG to bytes
            frame_bytes = jpeg.tobytes()

            # Yield the frame to the client
            yield (b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n\r\n')

    except GeneratorExit:
        # If the client disconnects, unsubscribe from the stream
        if stream:
            camera_monitor.frame_stream.unsubscribe(stream)


# route for video streaming
@camera_blueprint.route('/camera/<camera_id>/live')
def camera(camera_id):
    """
    Returns the live video stream for the given camera_id.
    """
    camera_id = int(camera_id)
    camera_monitor = None
    if hasattr(current_app, 'camera_monitors'):
        camera_monitor = current_app.camera_monitors.get(camera_id)

        if camera_monitor is None:
            return Response("Camera monitor not found", status=404)

    return Response(generate_frames(camera_monitor),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

vigi/templates/live/index.html
{% extends "base.html" %}

{% block title %}Live View{% endblock %}
{% block content %}
<div class="container">
  <h1>Live View</h1>

  <div class="d-flex align-content-start flex-wrap">
    {% for camera in cameras %}
      <a data-bs-toggle="modal" data-bs-target="#live_video_modal">
        <div class="card live_video_card me-2" style="width: 20rem;">
          <img class="card-img-top live_view_img" alt="camera stream" src="{{ url_for('camera.camera', camera_id=camera.id) }}">
          <div class="card-body">
            <h5 class="card-title">Camera #{{ camera.id }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ camera.frame_width }}x{{ camera.frame_height }}@{{ camera.fps }} FPS</h6>
            <p class="card-text">Online since {{ camera.start_time.strftime("%Y-%m-%d %H:%M:%S") }}</p>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>
</div>

<!-- Modal to show the live video -->
<div class="modal fade" id="live_video_modal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="modalTitle">Live video</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img class="card-img-top" id="live_video_modal_img" alt="camera stream" src="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}